import type { Genre } from '@/types';

// ジャンルの表示名マッピング
export const genreDisplayNames: Record<Genre, string> = {
  hiphop: 'ヒップホップ',
  rock: 'ロック',
  visualkei: 'V系',
  citypop: 'シティポップ',
  edm: 'EDM',
  jazz: 'ジャズ',
  rnb: 'R&B',
  punk: 'パンク',
  jpop: 'J-POP',
  kpop: 'K-POP',
  metal: 'メタル',
  indie: 'インディー',
  shoegaze: 'シューゲイザー',
  postrock: 'ポストロック',
  mathrock: 'マスロック',
  idol: 'アイドル',
  anisong: 'アニソン',
  vocaloid: 'ボカロ',
  enka: '演歌',
  classical: 'クラシック',
  ambient: 'アンビエント',
  reggae: 'レゲエ',
  soul: 'ソウル',
  funk: 'ファンク',
  trap: 'トラップ',
  lofi: 'Lo-Fi',
  house: 'ハウス',
  techno: 'テクノ',
  blues: 'ブルース',
  folk: 'フォーク',
  latin: 'ラテン',
  ska: 'スカ',
  hardcore: 'ハードコア',
  emo: 'エモ',
};

// ジャンルのTailwindカラークラス
export const genreColors: Record<Genre, string> = {
  hiphop: 'text-hiphop',
  rock: 'text-rock',
  visualkei: 'text-visualkei',
  citypop: 'text-citypop',
  edm: 'text-edm',
  jazz: 'text-jazz',
  rnb: 'text-rnb',
  punk: 'text-punk',
  jpop: 'text-jpop',
  kpop: 'text-kpop',
  metal: 'text-metal',
  indie: 'text-indie',
  shoegaze: 'text-shoegaze',
  postrock: 'text-postrock',
  mathrock: 'text-mathrock',
  idol: 'text-idol',
  anisong: 'text-anisong',
  vocaloid: 'text-vocaloid',
  enka: 'text-enka',
  classical: 'text-classical',
  ambient: 'text-ambient',
  reggae: 'text-reggae',
  soul: 'text-soul',
  funk: 'text-funk',
  trap: 'text-trap',
  lofi: 'text-lofi',
  house: 'text-house',
  techno: 'text-techno',
  blues: 'text-blues',
  folk: 'text-folk',
  latin: 'text-latin',
  ska: 'text-ska',
  hardcore: 'text-hardcore',
  emo: 'text-emo',
};

export const genreBgColors: Record<Genre, string> = {
  hiphop: 'bg-hiphop',
  rock: 'bg-rock',
  visualkei: 'bg-visualkei',
  citypop: 'bg-citypop',
  edm: 'bg-edm',
  jazz: 'bg-jazz',
  rnb: 'bg-rnb',
  punk: 'bg-punk',
  jpop: 'bg-jpop',
  kpop: 'bg-kpop',
  metal: 'bg-metal',
  indie: 'bg-indie',
  shoegaze: 'bg-shoegaze',
  postrock: 'bg-postrock',
  mathrock: 'bg-mathrock',
  idol: 'bg-idol',
  anisong: 'bg-anisong',
  vocaloid: 'bg-vocaloid',
  enka: 'bg-enka',
  classical: 'bg-classical',
  ambient: 'bg-ambient',
  reggae: 'bg-reggae',
  soul: 'bg-soul',
  funk: 'bg-funk',
  trap: 'bg-trap',
  lofi: 'bg-lofi',
  house: 'bg-house',
  techno: 'bg-techno',
  blues: 'bg-blues',
  folk: 'bg-folk',
  latin: 'bg-latin',
  ska: 'bg-ska',
  hardcore: 'bg-hardcore',
  emo: 'bg-emo',
};

export const genreBorderColors: Record<Genre, string> = {
  hiphop: 'border-hiphop',
  rock: 'border-rock',
  visualkei: 'border-visualkei',
  citypop: 'border-citypop',
  edm: 'border-edm',
  jazz: 'border-jazz',
  rnb: 'border-rnb',
  punk: 'border-punk',
  jpop: 'border-jpop',
  kpop: 'border-kpop',
  metal: 'border-metal',
  indie: 'border-indie',
  shoegaze: 'border-shoegaze',
  postrock: 'border-postrock',
  mathrock: 'border-mathrock',
  idol: 'border-idol',
  anisong: 'border-anisong',
  vocaloid: 'border-vocaloid',
  enka: 'border-enka',
  classical: 'border-classical',
  ambient: 'border-ambient',
  reggae: 'border-reggae',
  soul: 'border-soul',
  funk: 'border-funk',
  trap: 'border-trap',
  lofi: 'border-lofi',
  house: 'border-house',
  techno: 'border-techno',
  blues: 'border-blues',
  folk: 'border-folk',
  latin: 'border-latin',
  ska: 'border-ska',
  hardcore: 'border-hardcore',
  emo: 'border-emo',
};

// ジャンルのHEXカラー値
export const genreHexColors: Record<Genre, string> = {
  hiphop: '#FFD700',
  rock: '#DC2626',
  visualkei: '#7C3AED',
  citypop: '#F9A8D4',
  edm: '#3B82F6',
  jazz: '#F59E0B',
  rnb: '#EC4899',
  punk: '#22C55E',
  jpop: '#FF6B6B',
  kpop: '#A855F7',
  metal: '#6B7280',
  indie: '#8B5CF6',
  shoegaze: '#C084FC',
  postrock: '#64748B',
  mathrock: '#06B6D4',
  idol: '#FB7185',
  anisong: '#F472B6',
  vocaloid: '#2DD4BF',
  enka: '#D97706',
  classical: '#FBBF24',
  ambient: '#818CF8',
  reggae: '#A3E635',
  soul: '#E879F9',
  funk: '#FB923C',
  trap: '#EF4444',
  lofi: '#94A3B8',
  house: '#FACC15',
  techno: '#22D3EE',
  blues: '#6366F1',
  folk: '#A78BFA',
  latin: '#F97316',
  ska: '#34D399',
  hardcore: '#B91C1C',
  emo: '#1E293B',
};

// 全ジャンルリスト（カテゴリ順）
export const allGenres: Genre[] = [
  // ポップ系
  'jpop', 'kpop', 'idol', 'anisong', 'vocaloid',
  // ヒップホップ・R&B
  'hiphop', 'trap', 'rnb', 'soul',
  // ロック系
  'rock', 'indie', 'punk', 'emo', 'hardcore', 'metal',
  // サブジャンル
  'visualkei', 'shoegaze', 'postrock', 'mathrock',
  // エレクトロ
  'edm', 'house', 'techno', 'lofi', 'ambient',
  // その他
  'jazz', 'blues', 'funk', 'citypop', 'folk', 'enka',
  'classical', 'reggae', 'ska', 'latin',
];
